[common]
server_addr = 8.162.13.106
#server_addr = nas.getput.eu.org
server_port = 7002
protocol = quic 
#protocol = tcp
token =69614cd064b3fac0e60c22ff0f566f65
#token = nas6110409
user=1f85a18b7851f145
#privilege_token = *** 


[myn3] 
type = tcp
remote_port = 50501
plugin = socks5
plugin_user = chuwoo
plugin_passwd = nas6110409
#use_encryption = true
use_compression = true
